version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t devops .
      - run: docker run devops:latest npm test

  deploy-qa:
    machine: true
    steps:
      - checkout
      - run: sh .circleci/deployments/qa.sh

  deploy-prod:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints: "12:1e:1f:59:af:f5:57:6e:3e:c6:4a:b2:96:d8:20:09"
      - run: sh .circleci/deployments/prod.sh

workflows:
  version: 2
  central_flow:
    jobs:
      - build
      - deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: /feature-.*/
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master