version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t devops .
      - run: docker run devops:latest npm test

  deploy-qa:
    machine: true
    steps:
      - run: sh .circleci/deployments/qa.sh

  deploy-prod:
    machine: true
    steps:
      - run: sh .circleci/deployments/prod.sh

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-qa:
          requires:
            - build
          filters:
            branches:
              only: /feature-.*/
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master