version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t devops .
      - run: docker run devops:latest npm test
      - run: sh .circleci/deployments/qa.sh